"""add assets, price_history, macro_indicators

Revision ID: 26414e5db68c
Revises: 66ba73ca262f
Create Date: 2026-04-03 11:37:55.258209

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "26414e5db68c"
down_revision: str | None = "66ba73ca262f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=30), nullable=True),
        sa.Column("currency", sa.String(length=5), nullable=False),
        sa.Column("decimal_places", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("ticker", name=op.f("uq_assets_ticker")),
    )
    op.create_index(
        "idx_assets_type",
        "assets",
        ["asset_type"],
        unique=False,
        postgresql_where="is_active = TRUE",
    )
    op.create_table(
        "macro_indicators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("indicator_code", sa.String(length=30), nullable=False),
        sa.Column("indicator_name", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("previous_value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("projection_90d", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("projection_365d", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("recession_probability", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("economic_cycle_phase", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_macro_indicators")),
    )
    op.create_index(
        op.f("ix_macro_indicators_indicator_code"),
        "macro_indicators",
        ["indicator_code"],
        unique=False,
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_price_history_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
    )
    op.create_index(op.f("ix_price_history_asset_id"), "price_history", ["asset_id"], unique=False)
    op.create_index(op.f("ix_price_history_time"), "price_history", ["time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_history_time"), table_name="price_history")
    op.drop_index(op.f("ix_price_history_asset_id"), table_name="price_history")
    op.drop_table("price_history")
    op.drop_index(op.f("ix_macro_indicators_indicator_code"), table_name="macro_indicators")
    op.drop_table("macro_indicators")
    op.drop_index("idx_assets_type", table_name="assets", postgresql_where="is_active = TRUE")
    op.drop_table("assets")
    # ### end Alembic commands ###
