"""add strategies table

Revision ID: 64a73bca7495
Revises: a3e9f1b2c4d5
Create Date: 2026-04-04 19:08:27.480489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a73bca7495'
down_revision: Union[str, None] = 'a3e9f1b2c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('risk_pct', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('tp1', sa.Float(), nullable=False),
    sa.Column('tp2', sa.Float(), nullable=False),
    sa.Column('tp3_trailing_atr_mult', sa.Float(), nullable=False),
    sa.Column('n_shares', sa.Float(), nullable=False),
    sa.Column('risk_amount', sa.Float(), nullable=False),
    sa.Column('rr_ratio', sa.Float(), nullable=False),
    sa.Column('atr_used', sa.Float(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('warning', sa.String(length=500), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_strategies_asset_id_assets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategies')
    # ### end Alembic commands ###
